name: projet
description: "Med-Pass - Your Medical Passport in your pocket"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5
  file_picker: ^10.3.8
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.1
  flutter_doc_scanner: ^0.0.16
  image: ^4.1.7
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_translation: ^0.13.0
  google_mlkit_language_id: ^0.12.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  flutter_pdfview: ^1.4.3
  share_plus: ^10.1.4
  pdfx: ^2.6.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
